import React from 'react';
import Section from './Section';
import { AlertTriangle } from 'lucide-react';

const EthicalDisclaimer = () => {
    return (
        <div className="bg-yellow-50 dark:bg-yellow-900/10 border-y border-yellow-100 dark:border-yellow-900/30 py-12 transition-colors duration-300">
            <div className="max-w-4xl mx-auto px-6 text-center">
                <div className="inline-flex items-center justify-center w-12 h-12 bg-yellow-100 dark:bg-yellow-900/30 text-yellow-600 dark:text-yellow-400 rounded-full mb-4">
                    <AlertTriangle className="w-6 h-6" />
                </div>
                <h2 className="text-2xl font-bold mb-4 text-gray-800 dark:text-gray-200">Ethical Disclaimer</h2>
                <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-6">
                    MedTrust is an <strong>educational and academic project</strong> demonstrating the potential of AI and Blockchain in healthcare.
                    The predictions generated by this system are based on machine learning models and should <strong>NOT</strong> be considered as a substitute for professional medical advice, diagnosis, or treatment.
                </p>
                <p className="font-medium text-gray-800 dark:text-gray-200">
                    Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
                </p>
            </div>
        </div>
    );
};

export default EthicalDisclaimer;
